Tests, Cypress: add Web Monetizisation shim, and sample test.
coilhq/coil-wordpress-plugin pull request #98
Opened 2020-10-15 11:51 UTC by paulgibbs

See COI20328-132

2020-10-15 12:21 UTC, Jss4646 requested changes

2020-10-15 12:21 UTC, Jss4646 commented on tests/cypress/support/commands.js
> +		var unixtime_ms = new Date().getTime();
var should be const/let

2020-10-20 14:40 UTC, pragmatictom approved these changes

2020-10-20 15:15 UTC, Jss4646 approved these changes

2020-10-20 15:16 UTC, merged